config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'

  get 'welcome/index'

  root 'welcome#index'

  resources :articles

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def new
  end

  def create
    @article = Article.new(article_params)
      @article.save
      redirect_to @article
  end

  def show
    @article = Article.find(params[:id])
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1 class="text-center"></h1>

<div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
        <h1 class="text-center">Todos los articulos</h1>
        <div class="row">
            <% @articles.each do |article| %>
                <div id="card-article" class="col-sm-12 col-md-5" >
                    <header>
                        <h3 class="text-center"><%= article.title.capitalize %></h3>
                    </header>
                    <p>
                        <%= article.text.capitalize %>
                    </p>
                    <p class="text-right">
                        <%= link_to "Ver más", article_path(article) %>
                    </p>
                    <footer>
                        <p class="text-right">
                            Fecha:
                            <span class="label label-default">
                                <%= "20-oct-1989" %>
                            </span>
                        </p>
                    </footer>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Nuevo articulo</h1>

<div class="row">
    <div class="col-sm-12 col-md-6 col-md-offset-3">
        <% if @article.errors.any?  %>
            <div class="alert alert-danger alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
                  <strong>Ocurrieron algunos errores</strong>
                  <ul>
                      <% @article.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                      <% end %>
                  </ul>
            </div>
        <% end %>
        <%= form_for :article, url: articles_path do |f| %>
            <div class="form-group">
                <%= f.label :title, "Titulo" %><br>
                <%= f.text_field :title, class:'form-control', rows: 20 %><br>
            </div>
            <div class="form-group">
                <%= f.label :text, "Contenido" %><br>
                <%= f.text_area :text, class:'form-control', id:"article-text"%><br>
            </div>
            <p class="text-right">
                <%= f.submit "Gurdar articulo", class: 'btn btn-primary' %>
            </p>
        <% end %>
        <%= link_to "Regresar", articles_path, class:'text-right' %>
    </div>
</div>

app/views/articles/show.html.erb
<h1 class= "text-center"><%= @article.title.capitalize %></h1>
<div class="row">
    <div class="col-sm-12 col-md-6 col-md-offset-3">
        <div class="well well-long">
            <p><%= @article.text.capitalize %></p>
        </div>
        <%= link_to "Regresar", articles_path, class:'text-right' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
       <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "Articulos", articles_path %>